[package]
name = "barostuff"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roxmltree = "0.14.1"
walkdir = "2"
csv = "1.1.6"
log = "0.4"
env_logger = "0.8"
regex= "1.4.6"